name: Hexo Deploy

on:
  push:
    branches:
      - main  # ç›‘å¬ main åˆ†æ”¯æ¨é€äº‹ä»¶

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ›ï¸ æ‹‰å–ä»£ç 
        uses: actions/checkout@v3
        with:
          submodules: true  # æ‹‰å–ä¸»é¢˜å­æ¨¡å—

      - name: ğŸ“¦ å®‰è£… Node.js ç¯å¢ƒ
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: ğŸ“¦ å®‰è£… Hexo ä¾èµ–
        run: |
          npm install -g hexo-cli
          npm install

      - name: ğŸš€ ç”Ÿæˆé™æ€æ–‡ä»¶
        run: |
          hexo clean
          hexo generate

      - name: ğŸ”‘ éƒ¨ç½²åˆ° GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.HEXO_DEPLOY_KEY }}
          publish_dir: ./public
